# Generated by Django 2.2.7 on 2019-11-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='travelPlaces1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('subtitle', models.CharField(max_length=250)),
                ('imgurl', models.CharField(max_length=250)),
                ('price', models.CharField(max_length=250)),
            ],
        ),
    ]
