# Generated by Django 2.2.7 on 2019-11-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelplaces1',
            name='offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='travelplaces1',
            name='imgurl',
            field=models.ImageField(upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='travelplaces1',
            name='price',
            field=models.IntegerField(),
        ),
    ]
