# Generated by Django 2.2.7 on 2019-11-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20191121_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pintrest', models.CharField(max_length=100)),
                ('twitter', models.CharField(max_length=250)),
                ('fb', models.CharField(max_length=250)),
                ('linkedin', models.CharField(max_length=250)),
                ('mail', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('landline', models.CharField(max_length=250)),
                ('mobileno', models.CharField(max_length=250)),
                ('offmail', models.CharField(max_length=250)),
                ('dribbble', models.CharField(max_length=250)),
                ('behance', models.CharField(max_length=250)),
            ],
        ),
    ]
