# Generated by Django 2.2.7 on 2019-11-26 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_subscribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='aboutus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('subcontent', models.TextField()),
                ('about_image', models.ImageField(upload_to='')),
                ('onlinecourses', models.IntegerField()),
                ('student', models.IntegerField()),
                ('teachers', models.IntegerField()),
                ('countries', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('descripition', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('emailid', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('departure', models.CharField(max_length=100)),
                ('arrival', models.CharField(max_length=100)),
                ('budget', models.IntegerField()),
            ],
        ),
    ]
