# Generated by Django 2.2.7 on 2019-11-26 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_aboutus_message_trip'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('descripition', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='descripition',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='image',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='name',
        ),
    ]
