# Generated by Django 2.2.7 on 2019-11-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20191126_0533'),
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagesrc', models.ImageField(upload_to='')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='placeimg',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
