# Generated by Django 2.2.7 on 2019-11-27 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20191126_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='aboutlink',
            field=models.TextField(default=''),
        ),
    ]
